version: '3.8'

services:
  twitter-video-downloader:
    build: .
    container_name: twitter-video-downloader
    ports:
      - "8000:8000"
    volumes:
      # Persistent cookie storage (create if doesn't exist)
      - ./cookies.txt:/app/cookies.txt
      # Optional: Mount for raw cookie files (create if doesn't exist)  
      - ./raw_cookies.json:/app/raw_cookies.json
    environment:
      - PYTHONUNBUFFERED=1
      - COOKIES_FILE=/app/cookies.txt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - twitter-downloader-network

  # Optional: Add a simple nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: twitter-downloader-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - twitter-video-downloader
    restart: unless-stopped
    networks:
      - twitter-downloader-network
    profiles:
      - production

  # Cloudflare Tunnel for public access
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run --token eyJhIjoiOTU0NDQ1OWM0ZTUzOTZkMjFlYzU3NDc1NGU0ODY4NmYiLCJ0IjoiNTQ5MTk5ZDUtMjVkYi00Mzk2LWFlOWEtNmUwMjQ2M2VlODdiIiwicyI6IllXVTNNbVkzTVdFdE5UbGlZUzAwTVdFMUxUaGhaakV0TkdRM01XTmtNamhoTnpndyJ9
    depends_on:
      - twitter-video-downloader
    restart: unless-stopped
    networks:
      - twitter-downloader-network
    profiles:
      - tunnel

networks:
  twitter-downloader-network:
    driver: bridge

volumes:
  cookies-data:
    driver: local 